<?php

/**
 * @file
 * Contains farm_asset_area.module.
 */

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\entity\BundleFieldDefinition;

/**
 * Implements hook_farm_entity_bundle_field_info().
 */
function farm_asset_area_farm_entity_bundle_field_info(EntityTypeInterface $entity_type, string $bundle) {
  $fields = [];

  // Add an intrinsic_area field to assets.
  if ($entity_type->id() == 'asset') {

    // The label depends on the system of measurement.
    $system_of_measurement = 'metric';
    if ($quantity_config = \Drupal::config('quantity.settings')) {
      $system_of_measurement = $quantity_config->get('system_of_measurement');
    }
    $label = $system_of_measurement == 'metric' ? t('Total hectares') : t('Total acres');

    $fields['intrinsic_area'] = BundleFieldDefinition::create('decimal')
      ->setLabel($label)
      ->setCardinality(1)
      ->setRequired(FALSE)
      ->setSettings([
        'precision' => 11,
        'scale' => 4,
      ])
      ->setDisplayOptions('view', [
        'label' => 'inline',
        'type' => 'number_decimal'
      ])
      ->setDisplayConfigurable('view', TRUE)
      ->setDisplayOptions('form', [
        'type' => 'number',
      ])
      ->setDisplayConfigurable('form', TRUE);

  }

  return $fields;
}
